// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNsKiwKjtPL3MG24TWGQAwmQTP6VI6erk',
    appId: '1:974046879682:android:e98f5f45c17d3c5a37805b',
    messagingSenderId: '974046879682',
    projectId: 'stately-ally-265304',
    storageBucket: 'stately-ally-265304.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCo8qwwp7wtL_elehWn7wsVLyrSkK-ztZk',
    appId: '1:974046879682:ios:74d51a7518ad257837805b',
    messagingSenderId: '974046879682',
    projectId: 'stately-ally-265304',
    storageBucket: 'stately-ally-265304.firebasestorage.app',
    androidClientId: '974046879682-vhpdqh93vrtp7rp8vr5nhj93m4na4c84.apps.googleusercontent.com',
    iosClientId: '974046879682-4n59rlv8to5032opbts22tv7a5bojme8.apps.googleusercontent.com',
    iosBundleId: 'com.stepcircle.stepCircle',
  );
}
